version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080
    volumes:
     - .:/app
     - static_volume:/app/static

volumes:
  static_volume: