# Generated by Django 3.2 on 2021-10-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_url', models.CharField(max_length=3000)),
                ('actual_url_shortened', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'url_bank',
            },
        ),
    ]
