# Generated by Django 3.2 on 2021-10-14 15:36

from django.db import migrations, models
import domain.models.url_bank


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlbank',
            name='expiration_date',
            field=models.DateTimeField(default=domain.models.url_bank.get_default_expiration_date),
        ),
        migrations.AddField(
            model_name='urlbank',
            name='md_five_hash',
            field=models.CharField(db_index=True, default='363933421bb4e2b1bb54c09fcaf101b0', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlbank',
            name='actual_url_shortened',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
